"""empty message

Revision ID: 4f18706edd02
Revises: c56e60fcc200
Create Date: 2019-05-15 13:15:41.497497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f18706edd02'
down_revision = 'c56e60fcc200'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('access', sa.Integer(), nullable=True))
    op.drop_column('user', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('user', 'access')
    # ### end Alembic commands ###
