"""empty message

Revision ID: 514f8e98067a
Revises: 6b7515d19929
Create Date: 2019-05-19 21:17:50.384048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '514f8e98067a'
down_revision = '6b7515d19929'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('option_user_id_fkey', 'option', type_='foreignkey')
    op.create_foreign_key(None, 'option', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'option', type_='foreignkey')
    op.create_foreign_key('option_user_id_fkey', 'option', 'restaurant', ['user_id'], ['id'])
    # ### end Alembic commands ###
