"""empty message

Revision ID: 5e1364908414
Revises: 514f8e98067a
Create Date: 2019-05-19 21:21:01.307612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e1364908414'
down_revision = '514f8e98067a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('option_name_key', 'option', type_='unique')
    op.drop_constraint('option_showname_key', 'option', type_='unique')
    op.drop_constraint('option_meta_key_key', 'option_meta', type_='unique')
    op.drop_constraint('option_meta_value_key', 'option_meta', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('option_meta_value_key', 'option_meta', ['value'])
    op.create_unique_constraint('option_meta_key_key', 'option_meta', ['key'])
    op.create_unique_constraint('option_showname_key', 'option', ['showname'])
    op.create_unique_constraint('option_name_key', 'option', ['name'])
    # ### end Alembic commands ###
