"""empty message

Revision ID: 6b7515d19929
Revises: f0c7314e435b
Create Date: 2019-05-19 21:14:18.781637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b7515d19929'
down_revision = 'f0c7314e435b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'category', 'user', ['user_id'], ['id'])
    op.add_column('option', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'option', 'restaurant', ['user_id'], ['id'])
    op.add_column('option_meta', sa.Column('option_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'option_meta', 'option', ['option_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'option_meta', type_='foreignkey')
    op.drop_column('option_meta', 'option_id')
    op.drop_constraint(None, 'option', type_='foreignkey')
    op.drop_column('option', 'user_id')
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.drop_column('category', 'user_id')
    # ### end Alembic commands ###
