"""empty message

Revision ID: c56e60fcc200
Revises: d99d47f2e7ba
Create Date: 2019-05-15 11:17:15.688229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c56e60fcc200'
down_revision = 'd99d47f2e7ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('gg_username', sa.String(length=80), nullable=True))
    op.alter_column('user', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('user', 'gg_username')
    # ### end Alembic commands ###
