"""empty message

Revision ID: d99d47f2e7ba
Revises: 1aa6e428b341
Create Date: 2019-05-15 11:09:09.637872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd99d47f2e7ba'
down_revision = '1aa6e428b341'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fb_username', sa.String(length=80), nullable=True))
    op.alter_column('user', 'firstname',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('user', 'lastname',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'lastname',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('user', 'firstname',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.drop_column('user', 'fb_username')
    # ### end Alembic commands ###
