"""empty message

Revision ID: f0c7314e435b
Revises: 4f18706edd02
Create Date: 2019-05-16 18:02:28.005871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0c7314e435b'
down_revision = '4f18706edd02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('qrcode',
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('restaurant', sa.Column('image_id', sa.Integer(), nullable=True))
    op.add_column('restaurant', sa.Column('qrcode_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'restaurant', 'image', ['image_id'], ['id'])
    op.create_foreign_key(None, 'restaurant', 'qrcode', ['qrcode_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'restaurant', type_='foreignkey')
    op.drop_constraint(None, 'restaurant', type_='foreignkey')
    op.drop_column('restaurant', 'qrcode_id')
    op.drop_column('restaurant', 'image_id')
    op.drop_table('qrcode')
    op.drop_table('image')
    # ### end Alembic commands ###
